version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
        - DB_URI=${DB_URI}
        - DB_NAME=${DB_NAME}
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
